### ISSUE TITLE
dart protobuf

### ISSUE THREAD

**Issue by ghost** [celrenheit/sandglass-grpc#2]
This will allow Sandglass and Flutter to talk to eat other. I can really understand if this is something your not interested in, so if dont feel compelled, but i really like Sandglass design and i recently moved to Flutter as i got sick of the fast changing JS and Mobile world.

If Flutter is new to you, here is a webpage that compares it to react:
https://jaxenter.com/flutter-dart-react-mobile-sdk-135054.html

Anyway, so here goes:
Easy to add to the current .sh

Dart has had protobuf for a while. Its ONYL protobuf 2.0, but they will move to 3 soon i expect.
https://github.com/dart-lang/dart-protoc-plugin

The cool this is that dart just recently starte dot support grpc.
https://github.com/dart-lang/grpc-dart

**Comment by celrenheit** [comment]
I am open to new languages.
However note that it might not be a good idea to expose sandglass directly to a user interface (besides an internal tool not exposed to the world).
The first step might be to include dart in this image which sandglass uses to build protos: https://github.com/znly/docker-protobuf

**Comment by ghost** [comment]
dokcer based building is geat and yes i can add dart there.

Le me explain my thoughts and feel free to correct me or advise me if you still think its a bad idea.
The reason i wanted to connect flutter for sandglass is because i am experimenting with offline editing and them reconciliation that needs a lamport clock ( which serf has).  A bit like how you can do offline edits in google docs and then when back online it updates and also show edits from others in real time, etc etc. I also think sandglass is great is because it gives the client the ability to 
do messaging using the event bus with other users.

Also the flutter client has its own badger DB locally as you can compile badger to run on mobies.
I will compile sandblast itself to run on the mobile.

SO the STACK:
Mobile
- Fluuer GUI
- Sandblast client as golang on mobile
Server
- Sandblast server in cloud.
- Some other stuff etc etc

**Comment by ghost** [comment]
Regarding exposing to the web. Yes I would put a proxy in from of course.
I just realised I did not address this point you raised.

**Comment by celrenheit** [comment]
Have look into [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) for this kind of google docs like use case ?
I would recommend not to use sandglass on the mobile where the ressources are pretty limited. Also the current instability of sandglass due to its youngness would make things too much complicated.
However, it is a good use case on the server side. Instead of treating them sequentially, you can insert them in sandglass and threat them asynchronously and hopefully fast.

**Comment by ghost** [comment]
Hey - got side tracked.

Yes I agree that using crdt and your ordering insertion would work.

I am using flutter grpc with golang grpc 
Flutter / dart has had official grpc support for 1 month now.
Very fast and high quality GUI results for mobile and desktop.

https://github.com/grpc/grpc-dart

https://medium.com/dartlang/announcing-official-grpc-support-for-dart-6c9b50357af6

For CRDT there is not much out there in golang or dart land still. Lots in JS.
So not quite sure what to do.
It's possible for now to use LWW rule which is what firebase and couchbase use. They also do tombstones and then garbage collection. This might work well with sandglass if you retain all mutations on the server that come in ?

**Comment by ghost** [comment]
Hey - got side tracked.

Yes I agree that using crdt and your ordering insertion would work.

I am using flutter grpc with golang grpc 
Flutter / dart has had official grpc support for 1 month now.
Very fast and high quality GUI results for mobile and desktop.

https://github.com/grpc/grpc-dart

https://medium.com/dartlang/announcing-official-grpc-support-for-dart-6c9b50357af6

For CRDT there is not much out there in golang or dart land still. Lots in JS.
So not quite sure what to do.
It's possible for now to use LWW rule which is what firebase and couchbase use. They also do tombstones and then garbage collection. This might work well with sandglass if you retain all mutations on the server that come in ?

**Comment by ghost** [comment]
i am closing this as its gone off track
